### PR TITLE
Allow startup without active robot pose

### PR DESCRIPTION
**Pull request by MichaelGrupp**
Waits for a limited time (default 1s) for the robot pose to be available, then asks the user if they want to start at the origin if there's no pose within that time.

This is much more friendly than hanging and not starting up at all if the pose is not yet available, especially since you can initialize the pose via termviz.

Custom wait times can be also set via flag `termviz --tf-wait-time 1234` (or `-t`) if needed.

image

Support for missing robot TF only requires two small changes in `send_pose.rs` and `viewport.rs`. Sensor data like laser scans is not displayed, but is shown normally as soon as the pose is available (either from an outside initialization or by sending a pose from termviz).

Relates to: https://github.com/carzum/termviz/issues/68 (better handling of losing TF while termviz is already running is not part of this PR here)

### CODE REVIEW

**Comment by MichaelGrupp** [comment]
CI was broken because of conflicting `image` versions cause by `tui-image`. See [here](https://github.com/carzum/termviz/actions/runs/8668127605/job/23772551664?pr=91) and my second commit for the fix.

**Review by MaxiMaerz — APPROVED** [review]
LGTM, The feature makes sense and helps with the stupid crash and the chicken egg problem.
I did not check the code in full detail.

**Review by carzum — APPROVED** [review]
Looks good to me. I do not see a good use case for a custom timeout though. @MichaelGrupp  did you have a use case in mind?

**Comment by MichaelGrupp** [comment]
I mainly put the timeout arg so it won't be hardcoded, in case there is some situation where you might want to change it without recompiling.

**Pull request merged**
